apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 1h0m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 5m
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: "9.14.2"             # adjust to the chart version you prefer
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    primary:
      auth:
        existingSecret: mysql-secret
        # Note: chart expects certain keys inside the secret:
        # - mysql-root-password  (root)
        # - mysql-password       (user)
        # - mysql-user           (user)

