apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MBPJtg==,iv:ht2imakRUA8BuJtfG3+cCTSkcECSzmCSsjDi3qe/0DY=,tag:Zo0Yb4YD46zqIRagUgJ2Dw==,type:str]
    password: ENC[AES256_GCM,data:jy5lcvOrUTyKYUg=,iv:XsvkGyZFkZMroj+rrNaKU9PKUzkZm0s2DZLa2U0x3RM=,tag:lcedr5JTUGb5AWzkt7qIpg==,type:str]
sops:
    age:
        - recipient: age18f6eruhf5l0wzmrl66ms4l2qgrmrf6w56xg3ejjl972jxv2qffass700gp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZEZXOFFLM1lzaVBLdUJ6
            b3lCaTFhQkNzUGVVb3ZWSW9GQU96QWRDbmp3CmtxZDY0TWtURjRIdGZHREpnVURZ
            eE5rbDFuRllHR1J1UlgwRHoya0twMU0KLS0tIDdZdDE2aDFYdWt6M0lpYVNyRGQz
            NVNSMmVObFkyajI3N1NpZHYyWXVmdGMKuxDlkPOsHX5ElzUxsuOzYlbr97IQiKXa
            imrxB1t2tbCbPERLWo/lsvoBWGKnpYitsGv15frp8dnMX572GY7xKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T09:24:36Z"
    mac: ENC[AES256_GCM,data:ns+3hVWOwDerZq5a9Zw+zbkU8R9QwY/qcdQTQnFJuUIB5hku2WcAKcwOBNaB1RwIWx/HLJmtYH7rNo70SEbyUrCFzVGEPiIcaCz+yLVaMhpPVghIg9zGuQ1aCs4GT0NwKAEjvJu+6uYPsPbYWCEiKr/ZCPfgy1tHkKuKyqn9seI=,iv:eD85JNgFPCkQt8kv6YwJIDR//KcwnWM/+YTH8eWkY3s=,tag:z4JtJZm57Mw5BcobIZsQog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
