apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:2.9.1
        args:
          - "-config.file=/etc/promtail/config.yaml"
        volumeMounts:
          - name: config
            mountPath: /etc/promtail
      volumes:
        - name: config
          configMap:
            name: promtail-config

